greenpeace/planet4-plugin-engagingnetworks

includes/pages_datatable.twig

Related to https://github.com/greenpeace/planet4-selenium-tests/pull/5

Update markup to be able to run automated tests better.

---

TESTING.md
admin/css/admin.css
admin/js/en_app.js
bin/install-wp-tests.sh
classes/class-loader.php
classes/controller/api/class-fields-controller.php
classes/controller/api/class-rest-controller.php
classes/controller/menu/class-controller.php
classes/controller/menu/class-fields-settings-controller.php
classes/model/class-fields-model.php
classes/view/class-view.php
composer.json
includes/fields_settings.twig
includes/fields_settings_templates.twig
phpunit.xml.dist
planet4-engagingnetworks.php
tests/bootstrap.php
tests/p4-testcase.php
tests/test-api.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

[Issue 2374](https://jira.greenpeace.org/browse/PLANET-2374)
[Issue 2396](https://jira.greenpeace.org/browse/PLANET-2396)

PLANET-2374, PLANET-2396 Fields settings

---

classes/controller/blocks/class-controller.php
classes/controller/blocks/class-enform-controller.php
classes/controller/class-ensapi-controller.php

Temp fix for issue with checked fields not appearing as checked when editing the ENForm block.
This is caused due to GET using the field names all in lower case.
Made sure we display only the Live EN pages inside the Select EN Page drop down menu.

PLANET-2155 display block enform

---

classes/controller/blocks/class-controller.php
classes/controller/blocks/class-enform-controller.php
classes/controller/class-ensapi-controller.php
includes/country_select.twig
includes/enform.twig

If supporter is logged in then use the email address to auto fill the EN form with his supporter data retrieved from EN.

PLANET-2593 auto fill en form

---

phpcs.xml.dist

Add PHPCodeSniffer rules file.
Ref: https://jira.greenpeace.org/browse/PLANET-2773?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

PLANET-2773 - Add configuration file in our php repos for defining coding lint standards

---

classes/controller/blocks/class-controller.php
classes/controller/blocks/class-enform-controller.php

Fix 2 issues that came up from UAT.
Questions/optins should now be visible even if user is not logged in or has no EN supporter record yet. Also refactored the excluded_fields part to avoid php notices for undefined indexes.

PLANET-2999 feature planet 2999 b

---

classes/controller/blocks/class-enform-controller.php
includes/enform.twig

Add description for button text field in enform block backend view
Change textdomain variable to hardcoded value

PLANET-3075 - EN form: default fields should be flagged

---

classes/controller/menu/class-settings-controller.php
includes/settings.twig

[JIRA-3159](https://jira.greenpeace.org/browse/PLANET-3159)

PLANET-3159 Added setting for frontend/second API user

---

admin/js/en_app.js
classes/model/class-questions-model.php
includes/enform.twig
includes/questions_settings_templates.twig

Add hidden and default value fields for en questions in question settings.
Define a default answer for an en question.
Define if an en question should be treated as a hidden field in the en form.
[Ref](https://jira.greenpeace.org/browse/PLANET-3187)

PLANET-3187 Add hidden and default value fields for en questions

---

classes/controller/blocks/class-enform-controller.php

A quick fix related to #79 
Pass default value of questions fields to frontend for non-hidden fields also.

PLANET-3187 Use default value of questions fields for visible fields also

---

admin/js/en_ui.js

Changing placement for a label, see: https://jira.greenpeace.org/browse/PLANET-3297

PLANET-3297: EN Form block: move fields introductory text to the right place

---

classes/controller/class-ensapi-controller.php
includes/enform.twig

Asterisk added to field on condition that they are mandatory.
Spacing fixed in class-ensapi-controller.php to pass phpcs tests.
Ref: https://jira.greenpeace.org/browse/PLANET-3335

Planet-3335: Add asterisk to required form fields

---

classes/controller/menu/class-enform-post-controller.php
planet4-engagingnetworks.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_real.php
vendor/composer/autoload_static.php

Created a new class that will register the new custom post type.
[Issue](https://jira.greenpeace.org/browse/PLANET-3403)

PLANET-3403 Add en forms custom post type

---

classes/controller/class-enform-fields-list-table.php

Override display_tablenav to prevent nonce generation.

PLANET-3408 Disable nonce for en fields list table

---

admin/css/admin_en.css
classes/controller/class-enform-questions-list-table.php
classes/controller/menu/class-enform-post-controller.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

Added available EN Questions to EN post page.
ref: https://jira.greenpeace.org/browse/PLANET-3409

Planet-3409 List available engaging networks questions

---

admin/css/admin_en.css
classes/controller/class-enform-questions-list-table.php
classes/controller/menu/class-enform-post-controller.php

[Issue ](https://jira.greenpeace.org/browse/PLANET-3486)

PLANET-3486 Add and populate opt-ins custom meta box 

---

admin/css/admin_en.css
admin/js/enforms.js
classes/controller/class-enform-fields-list-table.php
classes/controller/class-enform-questions-list-table.php
classes/controller/menu/class-enform-post-controller.php
includes/selected_enform_fields.twig
includes/selected_meta_box.twig

Combines PLANET-3488 & PLANET-3410 #99 .
Persist customized form fields to p4_enform meta field 'p4enform_fields'

PLANET-3488 Save p4 enform fields in custom meta field

---

admin/css/admin_en.css
admin/js/enforms.js
classes/controller/menu/class-enform-post-controller.php
includes/selected_enform_fields.twig
includes/selected_meta_box.twig

Customize edit en form page to render saved fields configuration.
Add tooltips for fields attributes.
Persist fields ordering.

PLANET-3505 Customize edit en form page

---

classes/controller/class-enform-fields-list-table.php

Remove filter fields function used to filter non tagged en fields
The other part of this issue was done as part of fixing a conflict for this #110 
Last commit here.
https://github.com/greenpeace/planet4-plugin-engagingnetworks/pull/110/commits

PLANET-3548 Show non tagged en fields in enform create edit page

---

admin/js/en_ui.js
classes/controller/blocks/class-enform-controller.php

Remove the confused and non needed anymore field seperator from the shortcake (since we dont show the fields anymore.

PLANET-3401 Remove non needed anymore fields seperator

---

includes/selected_enform_fields.twig

[Ref : 3577](https://jira.greenpeace.org/browse/PLANET-3577)

PLANET-3577 Remove default value setting for enform 'Text' fields

---

admin/js/enforms.js
classes/controller/menu/class-enform-post-controller.php

Persist email field default attributes to backbone model so they get persisted also in db

PLANET-3576 Save email field default attributes to database

---

includes/enblock.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3582

PLANET-3582: Content title and description are not visible in the frontend

---

classes/controller/menu/class-enform-post-controller.php

Allow enform shortcode rendering for admin ajax requests

PLANET-3581 Render enblock fields in visual/edit mode

---

includes/enblock.twig

See companion PR in blocks plugin.
Ref:  https://jira.greenpeace.org/browse/PLANET-3586

PLANET-3586: Show Counter Bar Inside side style EN form

---

TESTING.md
composer.json
composer.lock

Remove obsolete composer script

Add phpunit as dev dependency

---

admin/js/enforms.js
classes/controller/blocks/class-enblock-controller.php
classes/controller/blocks/class-enform-controller.php
classes/controller/class-ensapi-controller.php
classes/controller/menu/class-enform-post-controller.php
classes/controller/menu/class-pages-datatable-controller.php
classes/controller/menu/class-settings-controller.php
includes/enform_post.twig
includes/selected_enform_fields.twig
planet4-engagingnetworks.php

Retrieve labels for each locale for optins that get selected from the list.
Remove EN Pages menu.
Remove Question Settings menu.
Fixed few js errors.

PLANET-3543 optins update

---

admin/js/admin.js
admin/js/en_app.js
admin/js/en_ui.js
admin/js/en_ui_heading_view.js
classes/class-loader.php
classes/controller/blocks/class-enblock-controller.php
classes/controller/blocks/class-enform-controller.php
classes/controller/menu/class-enform-post-controller.php

PLANET-3592 fix eslint errors

---

classes/controller/blocks/class-enblock-controller.php

Wording of some of the labels and descriptions changed in EN Block edit page

PLANET-3589 Rename commands in EN form Block edit mode

---

.githooks/prepare-commit-msg
README.md
gulpfile.js

[Issue](https://jira.greenpeace.org/browse/PLANET-3622)

PLANET-3622 Add prepare-commit-msg git hook

---

admin/css/admin_en.css
admin/js/en_ui.js
admin/js/en_ui_heading_view.js

Ref: https://jira.greenpeace.org/browse/PLANET-3596

PLANET-3596: EN form - make "Content Title" and "Content Description" only available for "Form on side" style

---

admin/js/enforms.js
includes/enform_post.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3630

PLANET-3630: Engaging Networks Forms: Hidden Opt In field should have editable value

---

includes/enblock.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3524
This is a leftover from 331817fd1a3d789a29281c88c67ed9e4adbffda7

PLANET-3524 - Use consistent vertical spacing on all blocks

---

classes/class-loader.php

[JIRA 3714](https://jira.greenpeace.org/browse/PLANET-3714)

PLANET-3714 Load translations .mo files on plugin load

---

includes/enform_post.twig

Small fix for rendering correctly in frontend.

Planet 3711 question checkboxes b

---

admin/js/enforms.js
classes/controller/menu/class-enform-post-controller.php
includes/enform_post.twig

[JIRA 3727](https://jira.greenpeace.org/browse/PLANET-3727)

PLANET-3727 Respect EN checkbox opt-in Pre-check value on EN form

---

classes/controller/blocks/class-enblock-controller.php
includes/tease-thankyou.twig

PLANET-3804 enblock field renames

---

classes/controller/blocks/class-enblock-controller.php
includes/tease-thankyou.twig

Change EN Block field label/names.

PLANET-3804 enblock field renames b

---

classes/controller/blocks/class-enblock-controller.php

Fix typo on EN Block field label.

PLANET-3804 enblock field renames c

---

admin/css/admin_en.css
classes/controller/blocks/class-enblock-controller.php
classes/controller/class-enform-fields-list-table.php
classes/controller/class-enform-questions-list-table.php

- Sort EN Form Field/Question/Optin lists alphabetically.
- Display normal fields before all non-tagged fields.
- Color differently the non-tagged fields.

PLANET-3849 sort field lists

---

classes/controller/blocks/class-enblock-controller.php
includes/enblock.twig

- Set h1 as the default header size so existing EN Blocks don't break

EN Block Header: Set h1 as default

---

classes/controller/blocks/class-enblock-controller.php
includes/tease-thankyou.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3872

PLANET-3872 EN Form: Add title and link on thankyou social buttons

---

includes/country_select.twig

[JIRA 4032](https://jira.greenpeace.org/browse/PLANET-4032)

PLANET-4032 EN Form block - Rename placeholder text in Country field

---

admin/js/en_ui.js
classes/controller/blocks/class-enblock-controller.php
includes/tease-thankyou.twig

- Checkbox added to show or hide donate button on thank you page

PLANET-4033 EN Form block - add option to remove Donate button from Thank you page

---

classes/controller/blocks/class-enblock-controller.php
includes/tease-thankyou.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3992
Add a function for constructing all share button metadata.

PLANET-3992 Use opengraph metadata for share buttons
